### PR TITLE
Add screening pipeline code to prolific branch

### PR DESCRIPTION
**Pull request by szorowi1**

### CODE REVIEW

**Comment by szorowi1** [comment]
Good points! To respond:

- That's correct -- we don't want to exclude participants based on inattentiveness for this study. I copied the code over for legacy reasons, but it is not invoked in the timeline. If we think it is confusing or distracting, I can remove it.
- And yes, because we haven't tested the SHAPS item yet I haven't included it in the would-be infrequency check. We need to collect some pilot data to figure out what a reasonable threshold would be.

Realizing now there's two additional points to discuss:

- Do we want to exclude participants for failing the comprehension check on the instructions twice or more? Or should we let all participants through regardless? 
- Have we decided on a performance bonus (e.g. $0.25)? If so, should it be based on accuracy or total points (fish)?

**Comment by danielbrianbennett** [comment]
Great, thanks.

> Do we want to exclude participants for failing the comprehension check on the instructions twice or more? Or should we let all participants through regardless?

I reckon let's let them through but record those data. It will be one more potential screening criterion to compare with the others.

> Have we decided on a performance bonus (e.g. $0.25)? If so, should it be based on accuracy or total points (fish)?

Feels fair to do this based on accuracy. How about something like (pseudocode) 
```
bonus = ((accuracy - 0.33) / 0.67) * 0.25
bonus = max(bonus, 0)
```
This gives a bonus of 0 for chance performance or worse, and otherwise a bonus proportional to degree of improvement over chance, up to a maximum of 25c for perfect performance.

**Comment by szorowi1** [comment]
Ok, I updated bonusing in d544f1d386f5c4817a08aed2267b081c83a2ca6e and nullified the instructions comprehension check in 1169f7b2486823cb98acfebca10973779feb8d0a. The number of errors in the comprehension check are still stored.

**Comment by danielbrianbennett** [comment]
Looks terrific, thanks Sam.

**Pull request merged**
